version: 2.1

orbs:
  node: circleci/node@4.5.1

jobs:
  ci-mac:
    macos:
      # xcode version defines the node version installed
      # See: https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
      xcode: 12.1.1 # This is node 15.1.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: 'yarn'
      - run: 'yarn run ci'

  ci-linux:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: 'yarn'
      - run: 'yarn run ci'

workflows:
  version: 2
  # On every commit: Build/Test/Lint
  commit:
    jobs:
      - ci-linux
      - ci-mac
